import { useState, useEffect } from 'react';
import { DashboardLayout } from '@/components/dashboard/DashboardLayout';
import { useAuthContext } from '@/contexts/AuthContext';
import { useCareerMatch } from '@/hooks/useCareerMatch';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import {
    TrendingUp,
    Target,
    Award,
    Activity,
    Brain,
    AlertCircle,
    CheckCircle2,
    Download,
    Loader2
} from 'lucide-react';
import { toast } from 'sonner';
import { useNavigate } from 'react-router-dom';
import { subscribeToUserProgress } from '@/services/userAnalyticsService';

export default function ProgressAnalytics() {
    const { user, profile } = useAuthContext();
    const { matches } = useCareerMatch();
    const navigate = useNavigate();

    const [analytics, setAnalytics] = useState({
        totalSkillsCompleted: 0,
        totalAssessmentsTaken: 0,
        avgScore: 0,
        totalCertificationsCompleted: 0,
        weeklyActivityCount: 0,
        monthlyGrowthRate: 0,
        engagementScore: 0,
        percentile: 0,
        hoursLearned: 0,
        roadmapCompletion: 0,
        projectCount: 0
    });

    const [loading, setLoading] = useState(true);
    const [downloadingReport, setDownloadingReport] = useState(false);

    useEffect(() => {
        if (!user) return;

        // Real-time listener for user progress
        const unsubscribe = subscribeToUserProgress(user.uid, (data) => {
            if (data) {
                // Calculate derived metrics from raw data
                const skillsCount = data.completedSkills?.length || 0;
                const certificationsCount = data.completedCertifications?.length || 0;
                const projectsCount = data.completedProjects?.length || 0;
                const roadmapProgress = data.completedSemesters ? Math.min(100, (data.completedSemesters.length) * 12.5) : 0; // Assuming 8 semesters total

                // Mock logic for activity count/growth if not explicitly tracked
                const activityCount = data.engagementScore ? Math.floor(data.engagementScore / 5) : 0;

                setAnalytics({
                    totalSkillsCompleted: skillsCount,
                    totalAssessmentsTaken: data.assessmentScore?.attempts || 0,
                    avgScore: data.assessmentScore?.lastScore || 0,
                    totalCertificationsCompleted: certificationsCount,
                    weeklyActivityCount: activityCount, // Using engagement as proxy for now
                    monthlyGrowthRate: 5 + (skillsCount * 2), // Mock growth based on skills
                    engagementScore: data.engagementScore || 0,
                    percentile: 75 + (projectsCount * 2), // Mock percentile
                    hoursLearned: (skillsCount * 2) + (projectsCount * 10), // Mock hours
                    roadmapCompletion: roadmapProgress,
                    projectCount: projectsCount
                });
            }
            setLoading(false);
        });

        return () => unsubscribe();
    }, [user]);

    // Matches
    const displayMatches = matches;
    const topMatch = matches[0];

    const handleDownloadReport = async () => {
        if (!user || !profile) return;
        setDownloadingReport(true);
        try {
            const reportContent = `
CAREER PROGRESS REPORT
User: ${profile.full_name || user.email}
Date: ${new Date().toLocaleDateString()}

METRICS
-------
Engagement Score: ${analytics.engagementScore}/100
Skills Completed: ${analytics.totalSkillsCompleted}
Assessments Taken: ${analytics.totalAssessmentsTaken} (Avg Score: ${analytics.avgScore}%)
Roadmap Progress: ${analytics.roadmapCompletion}%
Certifications: ${analytics.totalCertificationsCompleted}
Weekly Activity: ${analytics.weeklyActivityCount} actions

CAREER READINESS
----------------
Top Match: ${topMatch ? topMatch.pathName : 'N/A'}
Match Score: ${topMatch ? topMatch.matchScore : 0}%
Missing Skills: ${topMatch?.missingSkills?.join(', ') || 'None'}

Generated by CareerGrowth.
            `.trim();

            const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = `Analytics_${new Date().toISOString().split('T')[0]}.txt`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        } catch (error) {
            console.error(error);
            toast.error('Failed to download report');
        } finally {
            setDownloadingReport(false);
        }
    };

    if (loading) {
        return (
            <DashboardLayout>
                <div className="flex justify-center items-center h-[60vh]">
                    <Loader2 className="w-12 h-12 animate-spin text-primary" />
                </div>
            </DashboardLayout>
        );
    }

    return (
        <DashboardLayout>
            <div className="max-w-6xl mx-auto space-y-8 animate-fade-in">
                {/* Header */}
                <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
                    <div>
                        <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 rounded-full text-primary text-sm font-medium mb-4">
                            <Activity className="w-4 h-4" />
                            Intelligence Dashboard
                        </div>
                        <h1 className="text-3xl font-bold text-foreground">Progress Analytics</h1>
                        <p className="mt-2 text-muted-foreground">
                            Real-time insights into your career growth and market readiness.
                        </p>
                    </div>
                    <Button variant="outline" onClick={handleDownloadReport} disabled={downloadingReport}>
                        {downloadingReport ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Download className="w-4 h-4 mr-2" />}
                        Download Report
                    </Button>
                </div>

                {/* Main Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">Roadmap Progress</CardTitle>
                            <Target className="h-4 w-4 text-primary" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">{Math.round(analytics.roadmapCompletion)}%</div>
                            <Progress value={analytics.roadmapCompletion} className="h-2 mt-2" />
                            <p className="text-xs text-muted-foreground mt-2">Based on completed steps</p>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">Skills Mastered</CardTitle>
                            <Brain className="h-4 w-4 text-emerald-500" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">{analytics.totalSkillsCompleted}</div>
                            <p className="text-xs text-muted-foreground mt-1">
                                {analytics.totalCertificationsCompleted} Certifications Earned
                            </p>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">Engagement Score</CardTitle>
                            <Activity className="h-4 w-4 text-amber-500" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">{analytics.engagementScore}</div>
                            <p className={`text-xs mt-1 flex items-center gap-1 ${analytics.monthlyGrowthRate >= 0 ? 'text-green-500' : 'text-red-500'}`}>
                                <TrendingUp className="w-3 h-3" /> {analytics.monthlyGrowthRate}% vs last month
                            </p>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">Avg Assessment</CardTitle>
                            <Award className="h-4 w-4 text-purple-500" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">{analytics.avgScore}%</div>
                            <p className="text-xs text-muted-foreground mt-1">
                                {analytics.totalAssessmentsTaken} attempts total
                            </p>
                        </CardContent>
                    </Card>
                </div>

                {/* Career Match Section - Uses real data from useCareerMatch hook */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                    <Card className="lg:col-span-2">
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2">
                                <Target className="w-5 h-5 text-primary" /> Career Role Compatibility
                            </CardTitle>
                            <CardDescription>Based on your skills and assessments</CardDescription>
                        </CardHeader>
                        <CardContent className="space-y-6">
                            {displayMatches.length > 0 ? (
                                displayMatches.slice(0, 3).map((match: any, i: number) => (
                                    <div key={match.pathId || i} className="space-y-2">
                                        <div className="flex items-center justify-between">
                                            <div className="flex items-center gap-2">
                                                <span className={`flex items-center justify-center w-6 h-6 rounded-full text-xs font-bold ${i === 0 ? 'bg-primary text-primary-foreground' : 'bg-secondary text-muted-foreground'}`}>
                                                    {i + 1}
                                                </span>
                                                <h4 className="font-semibold">{match.pathName}</h4>
                                            </div>
                                            <span className="font-bold text-primary">{Math.round(match.matchScore)}% Match</span>
                                        </div>
                                        <Progress value={match.matchScore} className="h-2" />
                                        <div className="flex gap-2 text-xs text-muted-foreground ml-8">
                                            <span>Missing:</span>
                                            {match.missingSkills?.length > 0 ? (
                                                match.missingSkills.slice(0, 3).map((skill: string) => (
                                                    <span key={skill} className="px-1.5 py-0.5 bg-red-500/10 text-red-500 rounded">{skill}</span>
                                                ))
                                            ) : (
                                                <span className="text-green-500">None! You are ready.</span>
                                            )}
                                        </div>
                                    </div>
                                ))
                            ) : (
                                <div className="text-center py-8 text-muted-foreground">
                                    No career paths found. Please complete more details in your profile.
                                </div>
                            )}
                        </CardContent>
                    </Card>

                    {/* Recommendations */}
                    <div className="space-y-6">
                        <Card>
                            <CardHeader>
                                <CardTitle className="text-base flex items-center gap-2">
                                    <AlertCircle className="w-4 h-4 text-amber-500" /> Skill Gap Analysis
                                </CardTitle>
                            </CardHeader>
                            <CardContent>
                                {topMatch && topMatch.missingSkills?.length > 0 ? (
                                    <div className="space-y-4">
                                        <p className="text-sm text-muted-foreground">To reach <strong>{topMatch.pathName}</strong>, focus on:</p>
                                        <div className="flex flex-wrap gap-2">
                                            {topMatch.missingSkills.slice(0, 5).map((skill: string) => (
                                                <span key={skill} className="px-2 py-1 bg-secondary text-foreground text-xs font-medium rounded-md border border-border">{skill}</span>
                                            ))}
                                        </div>
                                        <Button className="w-full text-xs" variant="outline" size="sm" onClick={() => navigate('/roadmap')}>
                                            <Target className="w-3 h-3 mr-1" /> Update Roadmap
                                        </Button>
                                    </div>
                                ) : (
                                    <div className="text-center py-4">
                                        <CheckCircle2 className="w-8 h-8 text-green-500 mx-auto mb-2" />
                                        <p className="text-sm font-medium">You are on track!</p>
                                    </div>
                                )}
                            </CardContent>
                        </Card>

                        <div className="bg-gradient-to-br from-primary/10 to-transparent border border-primary/20 rounded-xl p-6">
                            <Brain className="w-8 h-8 text-primary mb-3" />
                            <h3 className="font-bold text-lg mb-1">AI Interview Prep</h3>
                            <p className="text-sm text-muted-foreground mb-4">Practice with real-time AI feedback.</p>
                            <Button className="w-full" onClick={() => navigate('/ai-mentor')}>
                                <Brain className="w-4 h-4 mr-2" /> Start Mock Interview
                            </Button>
                        </div>
                    </div>
                </div>
            </div>
        </DashboardLayout>
    );
}
